version : "3.9"

networks :
  inceptionet :
    name: inceptionet
    driver : bridge

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: volume
      o: 'bind'
      device: /home/youngpar/data/db
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: volume
      o: 'bind'
      device: /home/youngpar/data/wordpress

services :
  nginx :
    build : ./requirements/nginx
    image: nginx
    container_name : nginx
    restart : always
    depends_on :
      - wordpress
    ports :
      - 443:443
    networks :
      - inceptionet
    volumes :
      - wordpress:/var/www
    env_file:
      - .env

  wordpress :
    build : ./requirements/wordpress
    image: wordpress
    container_name : wordpress
    restart : always
    depends_on :
      - mariadb
    ports:
      - 9000:9000
    networks:
      - inceptionet
    volumes:
      - wordpress:/var/www
    env_file:
      - .env

  mariadb :
    build : ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    networks:
      - inceptionet
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env